build_settings:
    clone_depth: 1
    verbose: true
    ignore:
        - "tests"
        - "vendor"

test:
    lint:
        directories:
          - "src/"
          - "tests/"
    php_loc:
        directory: "src"
    php_unit:
      
complete:
    clean_build:
        remove:
            - vendor